insert into Category (created, name) values(now(), 'C#');
insert into Category (created, name) values(now(), 'CI&D');
insert into Category (created, name) values(now(), 'Git');
insert into Category (created, name) values(now(), 'Build');
insert into Category (created, name) values(now(), 'SDLC');
insert into Category (created, name) values(now(), 'Culture');
insert into Category (created, name) values(now(), 'Communication');
insert into Category (created, name) values(now(), 'Leadership');
insert into Category (created, name) values(now(), 'Requirements');
insert into Category (created, name) values(now(), 'Unit Testing');
insert into Category (created, name) values(now(), 'iPad');
insert into Category (created, name) values(now(), 'Web Development');
insert into Category (created, name) values(now(), 'OSX');
insert into Category (created, name) values(now(), 'Facebook');
insert into Category (created, name) values(now(), 'AJAX');
insert into Category (created, name) values(now(), 'iOS');
insert into Category (created, name) values(now(), 'Ruby On Rails');
insert into Category (created, name) values(now(), 'SQL');
insert into Category (created, name) values(now(), 'HTML');
insert into Category (created, name) values(now(), '.Net');
insert into Category (created, name) values(now(), 'asp.net');
insert into Category (created, name) values(now(), 'vb.net');
insert into Category (created, name) values(now(), 'mvc');
insert into Category (created, name) values(now(), 'SharePoint');
insert into Category (created, name) values(now(), 'debug');
insert into Category (created, name) values(now(), 'C++');
insert into Category (created, name) values(now(), 'Android');
insert into Category (created, name) values(now(), 'iPhone');
insert into Category (created, name) values(now(), 'jquery');
insert into Category (created, name) values(now(), 'PHP');
insert into Category (created, name) values(now(), 'Java');
insert into Category (created, name) values(now(), 'Javascript');
insert into Category (created, name) values(now(), 'SQL');
insert into Category (created, name) values(now(), 'UX');
insert into Category (created, name) values(now(), 'QA');
insert into Category (created, name) values(now(), 'Software Development');
insert into Category (created, name) values(now(), 'Career');
insert into Category (created, name) values(now(), 'Linux');
insert into Category (created, name) values(now(), 'Server');
insert into Category (created, name) values(now(), 'Network');
insert into Category (created, name) values(now(), 'TCP/IP');
insert into Category (created, name) values(now(), 'Windows');
insert into Category (created, name) values(now(), 'Server Roles');
insert into Category (created, name) values(now(), 'Active Directory');
insert into Category (created, name) values(now(), 'Group Policy');
insert into Category (created, name) values(now(), 'Security');
insert into Category (created, name) values(now(), 'Agile');
insert into Category (created, name) values(now(), 'Scrum');
insert into Category (created, name) values(now(), 'Database');
insert into Category (created, name) values(now(), 'Oracle');
insert into Category (created, name) values(now(), 'Sales');
insert into Category (created, name) values(now(), 'Product Management');
insert into Category (created, name) values(now(), 'Product Owner	');
insert into Category (created, name) values(now(), 'Object- oriented programming	');
insert into Category (created, name) values(now(), 'Problem solving');
insert into Category (created, name) values(now(), 'Marketing');
insert into Category (created, name) values(now(), 'Strategy');
insert into Category (created, name) values(now(), 'Human Resources');
insert into Category (created, name) values(now(), 'Recruiting');
insert into Category (created, name) values(now(), 'FileNet');
insert into Category (created, name) values(now(), 'Content Engine	');
insert into Category (created, name) values(now(), 'Information Security');
insert into Category (created, name) values(now(), 'Implementation	');
insert into Category (created, name) values(now(), 'Data Warehouse');
insert into Category (created, name) values(now(), 'Data Conversion');
insert into Category (created, name) values(now(), 'Data Analysis');
insert into Category (created, name) values(now(), 'CSS');
insert into Category (created, name) values(now(), 'Accounting');
insert into Category (created, name) values(now(), 'Social Media');
insert into Category (created, name) values(now(), 'Wordpress');
insert into Category (created, name) values(now(), 'Information Assurance');
insert into Category (created, name) values(now(), 'mySQL');
insert into Category (created, name) values(now(), 'Perl');
insert into Category (created, name) values(now(), 'Mobile Development');
insert into Category (created, name) values(now(), 'Apache');
insert into Category (created, name) values(now(), 'WebLogic');
insert into Category (created, name) values(now(), 'Leadership');
insert into Category (created, name) values(now(), 'Management');
insert into Category (created, name) values(now(), 'Business');
insert into Category (created, name) values(now(), 'Integration');
insert into Category (created, name) values(now(), 'Government');


select * from Category;