# --- !Ups

ALTER TABLE Candidate DROP FOREIGN KEY FK95C3B563399E12F6;
ALTER TABLE Candidate DROP COLUMN job_id;

# --- !Downs

ALTER TABLE Candidate ADD COLUMN job_id bigint(20);
ALTER TABLE Candidate ADD CONSTRAINT FK95C3B563399E12F6 FOREIGN KEY (job_id) REFERENCES Job (id);